### ISSUE TITLE
Hosting on Heroku or Alternatives?

### ISSUE THREAD

**Issue by joshmgrant** [saucelabs/the-internet#80]
Hello there! Since [Heroku is ending its free tier support](https://techcrunch.com/2022/08/25/heroku-announces-plans-to-eliminate-free-plans-blaming-fraud-and-abuse/), I would like to know the future of this project on Heroku (since it's right there in the URL). Are there plans to upgrade to a paid Heroku account? Or move to a different PaaS provider? I'm more than happy to help out here with configuration or suggestions. Thanks so much!

**Comment by diemol** [comment]
Hi, and apologies for the very late response. This project will continue to be maintained, and Sauce Labs is paying for the Heroku account. 
The Internet will be around for a long time :)
