### ISSUE TITLE
Website is down :-(

### ISSUE THREAD

**Issue by christian-bromann** [saucelabs/the-internet#83]
It seems that https://the-internet.herokuapp.com/ is down, was there a plan at Sauce Labs to not host this web site anymore?

**Comment by jan-molak** [comment]
It looks like http://elementalselenium.com/ is down too

**Comment by jan-molak** [comment]
@christian-bromann looks like the websites are back up

**Comment by christian-bromann** [comment]
Glad it was just a blip and not taken down indefinitely.
